import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowUp, ArrowUpRight, Check, ChevronLeft, Keyboard, Lock, Mic, MicOff, Minus, Phone, PhoneOff, RotateCcw, Volume2, VolumeX, X } from 'lucide-react';
import { api } from './lib/api';
import { Call, voiceSupport } from './lib/call';
import { connectGmail, preloadGmail, simulatedGmail } from './lib/gmail';

const A='/design-v7/assets';
const Mark=()=> <img src={`${A}/mark.svg`} alt=""/>;
function useViewport(){const [s,setS]=useState(()=>({W:innerWidth||1440,H:innerHeight||900}));useEffect(()=>{const u=()=>setS({W:innerWidth||1440,H:innerHeight||900});addEventListener('resize',u);return()=>removeEventListener('resize',u)},[]);return s}
function geometry(W,H,open,connected,scene){const mobile=W<650,short=!mobile&&H<=680,wide=!mobile&&W>=820&&connected&&scene!=='voice'&&scene!=='incoming';const headH=mobile?72:94,footH=mobile?44:50,worldH=H-headH-footH;const stageW=mobile?1.8*W:W,stageH=stageW*9/16,stageL=mobile?-.4*W:0,stageT=mobile?worldH-.14*H-stageH:worldH+.07*W-stageH;const ringX0=stageL+.4905*stageW,ringY0=stageT+.4722*stageH;const ringX=W*.5,ringY=worldH-(mobile?92:short?48:104),tx=ringX-ringX0,ty=ringY-ringY0,scale=mobile?1.12:short?1.12:1.26;let panelW,panelH,panelTop,panelL;if(mobile){panelTop=8;panelW=W-28;panelL=14;panelH=Math.max(400,ringY-58-panelTop)}else{panelW=Math.min(short?400:wide?900:440,W-80);panelTop=short?0:W>=1600?40:16;panelL=(W-panelW)/2;const strap=.105*stageH*scale+18;panelH=short?ringY-38-panelTop:Math.min(700,Math.max(280,ringY-strap-panelTop))}return{W,H,mobile,short,wide,headH,footH,worldH,stageW,stageH,stageL,stageT,ringX,ringY,tx,ty,scale,panelW,panelH,panelTop,panelL,open}}

export default function App(){
 const {W,H}=useViewport();
 const [state,setState]=useState(null),[config,setConfig]=useState(null),[error,setError]=useState('');
 const [open,setOpen]=useState(false),[sheet,setSheet]=useState(null),[name,setName]=useState(''),[text,setText]=useState('');
 const [busy,setBusy]=useState(false),[gmailBusy,setGmailBusy]=useState(false),[view,setView]=useState('text');
 const [status,setStatus]=useState('idle'),[caption,setCaption]=useState(''),[muted,setMuted]=useState(false),[level,setLevel]=useState(0);
 const [filmSrc,setFilmSrc]=useState(''),[intro,setIntro]=useState(false),[mediaReady,setMediaReady]=useState(false),[mediaFailed,setMediaFailed]=useState(false),[pressing,setPressing]=useState(false),[closing,setClosing]=useState(false),[soundOn,setSoundOn]=useState(true);
 const video=useRef(null),canvas=useRef(null),frames=useRef([]),framesReady=useRef(false),panel=useRef(null),messages=useRef(null),call=useRef(null),active=useRef(false),session=useRef(null),serial=useRef(Promise.resolve()),timers=useRef([]),reduced=useRef(false),filmUrl=useRef(''),introRaf=useRef(0),pressRaf=useRef(0),motion=useRef({});
 session.current=state;motion.current={open,pressing,closing,intro,mediaReady};const live=!['idle','ended'].includes(status),agent=state?.agentName||'Your Persona';const lastAgent=[...(state?.transcript||[])].reverse().find(m=>m.role==='agent');const incoming=!live&&['incoming_call','call_offer'].includes(lastAgent?.card?.type)&&!lastAgent?.card?.closed;const scene=(!state?.agentName&&!state?.transcript?.length)?'naming':live&&view==='voice'?'voice':incoming?'incoming':'chat';const connected=state?.gmail?.status==='connected';const g=useMemo(()=>geometry(W,H,open,connected,scene),[W,H,open,connected,scene]);
 const later=(ms,fn)=>{const id=setTimeout(fn,ms);timers.current.push(id);return id};const apply=r=>{setState(r.state);session.current=r.state;return r};const event=async ev=>apply(await api.event(session.current.id,ev));
 useEffect(()=>{reduced.current=matchMedia?.('(prefers-reduced-motion: reduce)').matches||false;let alive=true;(async()=>{try{const [r,c]=await Promise.all([api.resume(),api.config()]);if(!alive)return;apply(r);setConfig(c);preloadGmail(c.googleClientId);const v=voiceSupport();await api.event(r.state.id,{type:'client_caps',voice:v.recognition&&v.synthesis})}catch{if(alive)setError('We couldn’t connect. Refresh to try again.')}})();return()=>{alive=false}},[]);
 useEffect(()=>{let alive=true;fetch(`${A}/hero.mp4`).then(r=>{if(!r.ok)throw new Error(`film ${r.status}`);return r.blob()}).then(blob=>{if(!alive)return;const url=URL.createObjectURL(blob);filmUrl.current=url;setFilmSrc(url)}).catch(()=>{if(alive)setFilmSrc(`${A}/hero.mp4`)});return()=>{alive=false;if(filmUrl.current)URL.revokeObjectURL(filmUrl.current)}},[]);
 useEffect(()=>{const id=setInterval(()=>{const v=video.current,m=motion.current;if(!v||m.intro||m.pressing||m.closing||m.open||!m.mediaReady||v.readyState<1)return;if(v.paused&&Math.abs(v.currentTime-4.6)>.08){try{v.currentTime=4.6}catch{}}},700);return()=>clearInterval(id)},[]);
 useEffect(()=>{const id=setTimeout(()=>{let loaded=0;frames.current=Array.from({length:85},(_,i)=>{const image=new Image();image.onload=()=>{if(++loaded===85)framesReady.current=true};image.src=`${A}/press/f${String(i).padStart(3,'0')}.jpg`;return image})},900);return()=>clearTimeout(id)},[]);
 useEffect(()=>{if(messages.current)messages.current.scrollTop=messages.current.scrollHeight},[state?.transcript?.length,busy,scene]);
 useEffect(()=>{if(!open)return;const id=setTimeout(()=>(panel.current?.querySelector('input,button'))?.focus({preventScroll:true}),850);const key=e=>{if(e.key==='Escape'){if(sheet)setSheet(null);else close()}};addEventListener('keydown',key);return()=>{clearTimeout(id);removeEventListener('keydown',key)}},[open,sheet]);
 useEffect(()=>{const h=()=>{if(active.current&&session.current)api.beacon(session.current.id,{type:'call_ended',reason:'tab_closed'})};addEventListener('pagehide',h);return()=>removeEventListener('pagehide',h)},[]);useEffect(()=>()=>{timers.current.forEach(clearTimeout);cancelAnimationFrame(introRaf.current);cancelAnimationFrame(pressRaf.current);active.current=false;call.current?.end('user')},[]);
 const sfx=on=>{if(!soundOn)return;try{const AC=window.AudioContext||window.webkitAudioContext,ac=new AC(),o=ac.createOscillator(),gain=ac.createGain();o.type='sine';o.frequency.value=on?680:340;gain.gain.setValueAtTime(.04,ac.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.09);o.connect(gain).connect(ac.destination);o.start();o.stop(ac.currentTime+.09);later(160,()=>ac.close())}catch{}};
 const settleFilm=()=>{cancelAnimationFrame(introRaf.current);const v=video.current;if(v){v.pause();try{v.currentTime=4.6}catch{}}setIntro(false);setMediaReady(true)};
 const prepareFilm=e=>{const v=e.currentTarget;v.muted=true;v.defaultMuted=true;if(reduced.current){try{v.currentTime=4.6}catch{}setMediaReady(true);return}setIntro(true);setMediaReady(true);try{v.currentTime=0;v.playbackRate=1;const p=v.play();p?.catch(settleFilm)}catch{settleFilm();return}const tick=()=>{if(v.currentTime>=4.58){settleFilm();return}if(!v.paused)introRaf.current=requestAnimationFrame(tick)};introRaf.current=requestAnimationFrame(tick);later(6600,()=>{if(motion.current.intro)settleFilm()})};
 const pulse=()=>{document.documentElement.style.setProperty('--ring-flash','1');later(600,()=>document.documentElement.style.setProperty('--ring-flash','0'))};const toActive=()=>{const v=video.current;if(v){v.pause();try{v.currentTime=12}catch{}}};const reopen=()=>{sfx(true);pulse();setOpen(true);later(120,toActive)};
 const awaken=()=>{if(intro){settleFilm();return}if(open||pressing||closing)return;const v=video.current;if(reduced.current||mediaFailed||!mediaReady||!v){reopen();return}setPressing(true);let touched=false;const rate=1.5,TOUCH=6.15,END=8.2,events=['timeupdate','pause','stalled','error'];const cleanup=()=>events.forEach(n=>v.removeEventListener(n,onEvent));const touch=()=>{if(touched)return;touched=true;cleanup();setPressing(false);try{v.playbackRate=3.2}catch{}reopen()};const onEvent=e=>{if(e.type==='timeupdate'){if(v.currentTime>=TOUCH)touch()}else touch()};later(((TOUCH-4.6)/rate)*1000+250,touch);try{v.pause();v.currentTime=4.6;v.playbackRate=rate;const p=v.play();p?.then(()=>events.forEach(n=>v.addEventListener(n,onEvent))).catch(touch)}catch{touch();return}const tick=()=>{if(!touched&&v.currentTime>=TOUCH)touch();if(v.currentTime>=END||v.ended){v.pause();toActive();return}if(!v.paused)pressRaf.current=requestAnimationFrame(tick)};pressRaf.current=requestAnimationFrame(tick)};
 const minimize=()=>{if(open){sfx(false);setOpen(false);setSheet(null);later(950,()=>{const v=video.current;if(v){v.pause();try{v.currentTime=4.6}catch{}}})}};
 const close=()=>{if(closing||!open)return;if(reduced.current||!framesReady.current||!canvas.current){pulse();minimize();return}setClosing(true);setSheet(null);const ctx=canvas.current.getContext('2d'),rate=1.5,from=79,touch=37,fps=24*rate,start=performance.now();let tucked=false;const draw=()=>{const i=Math.max(0,Math.round(from-(performance.now()-start)/1000*fps)),image=frames.current[i];if(image?.complete)ctx.drawImage(image,0,0,1280,720);if(i<=touch&&!tucked){tucked=true;pulse();minimize()}if(i<=0){setClosing(false);const v=video.current;if(v){v.pause();try{v.currentTime=4.6}catch{}}return}requestAnimationFrame(draw)};draw()};
 const speak=async r=>{if(!active.current)return;const m=[...(r.messages||[])].reverse().find(m=>m.role==='agent');if(m){await call.current?.speak(m.text);if(m.card?.type==='end_call')call.current?.end('agent')}else call.current?.listening()};
 const send=(value,via='text')=>{if(!value.trim()||!session.current)return;setError('');setBusy(true);serial.current=serial.current.catch(()=>{}).then(async()=>{try{const r=apply(await api.turn(session.current.id,value,via));await speak(r)}catch{setError('That message didn’t send. Your draft is here to retry.');setText(value)}finally{setBusy(false)}})};
 const startCall=async()=>{if(call.current||!session.current)return;setView('voice');setOpen(true);setError('');setMuted(false);const c=new Call({onStatus:setStatus,onLevel:setLevel,onCaption:setCaption,onUtterance:t=>send(t,'voice'),onReprompt:(_,strike)=>event({type:'silence_prompt',strike}).catch(()=>{}),onEnd:(reason,info)=>{const was=active.current;active.current=false;call.current=null;setView('text');setCaption('');if(was)event({type:'call_ended',reason,...info}).catch(()=>setError('Couldn’t save the call ending.'));else if(['mic_denied','unsupported'].includes(reason))event({type:'call_unavailable',reason}).catch(()=>{})}});call.current=c;await c.start();if(c.status==='ended'||call.current!==c)return;active.current=true;try{await speak(await event({type:'call_started'}))}catch{c.end('error')}};
 const decline=async()=>{try{await event({type:'call_declined'})}catch{setError('Couldn’t save that. Please try again.')}};const endCall=()=>call.current?.end('user');
 const gmail=async(sample=false)=>{if(gmailBusy)return;setGmailBusy(true);setError('');try{const result=sample?simulatedGmail():await connectGmail(config.googleClientId);await speak(await event({type:'gmail_connected',...result}));setSheet(null)}catch(e){setError('Gmail didn’t connect. You can retry or keep going.');await event({type:'gmail_failed',error:e.message}).catch(()=>{})}finally{setGmailBusy(false)}};
 const reset=async()=>{if(live)endCall();try{await event({type:'forget'});setName('');setSheet(null);setView('text');setText('');close()}catch{setError('Couldn’t reset. Your conversation is still here.')}};
 const radius=.0167*g.stageW*g.scale,ringTop=g.ringY-radius*.55,panelBottom=g.panelTop+g.panelH-2;const panelClosed=`translate3d(0,${g.ringY-(g.panelTop+g.panelH)}px,-200px) rotateX(-74deg) scale(.4)`;const stageTransform=open?`translate3d(${g.tx}px,${g.ty}px,0) rotate(-1.5deg) scale(${g.scale})`:'translate3d(0,0,0) rotate(0) scale(1)';const titleStyle={left:g.mobile?'28px':W>=1600?'12%':W<1050?'6%':'8%',top:g.mobile?24:W>=1600?60:30,opacity:open?(g.mobile||W<1050?0:.3):1,transform:`translateY(${open?-22:0}px)`,filter:`blur(${open?3:0}px)`};const transcript=(state?.transcript||[]).filter(m=>m.role!=='system'||/call|gmail|text/i.test(m.text));
 return <div className="exact-app"><div className="exact-frame" style={{height:H}}><header className="exact-head" style={{height:g.headH,padding:`0 ${g.mobile?'22px':'5%'}`}}><a href="#" className="exact-wordmark"><Mark/><span>Persona</span></a>{!g.mobile&&<span className="exact-headnote">A little closer.</span>}<div className="exact-head-actions"><button className="exact-sound" onClick={()=>setSoundOn(v=>!v)}>{soundOn?<Volume2 size={16}/>:<VolumeX size={16}/>}</button><button onClick={()=>{if(!open)reopen();setSheet('reset')}}>Start over</button></div></header>
 <main className="exact-world" style={{top:g.headH,bottom:g.footH,perspectiveOrigin:`${g.ringX}px ${g.ringY}px`}}><div className="exact-title" style={titleStyle}><span>MEET YOUR PERSONA</span><h1 style={{fontSize:g.mobile?44:Math.round(Math.min(64,Math.max(40,.042*W)))}}>Your world.<br/>A little <em>lighter.</em></h1><p>One touch. A conversation that stays with you.</p></div>
 <div className="exact-stage" style={{left:g.stageL,top:g.stageT,width:g.stageW,height:g.stageH,transform:stageTransform,transition:open?'transform .6s cubic-bezier(.45,.05,.2,1) .08s':'transform .5s cubic-bezier(.45,.05,.2,1) .42s'}}><img src={`${A}/band-poster.jpg`} alt="Persona Band on a wrist" className="exact-media" style={{opacity:intro||pressing||closing?0:1}}/><video ref={video} src={filmSrc||undefined} muted playsInline preload="auto" className="exact-media" style={{opacity:filmSrc&&mediaReady&&(intro||pressing)&&!closing?1:0}} onLoadedMetadata={prepareFilm} onError={()=>{setIntro(false);setMediaFailed(true);setMediaReady(true)}}/><canvas ref={canvas} width="1280" height="720" className="exact-media" style={{opacity:closing?1:0}}/><div className={`exact-band-glow ${open?'on':''} ${incoming?'incoming':''} ${live?status:''}`} style={{'--level':level}}/><button className="exact-ring-hit" onClick={open?close:awaken} aria-label={intro?'Skip intro':open?'Minimize to the ring':'Touch the ring to meet your Persona'}/>{!intro&&!open&&!pressing&&!closing&&<div className="exact-touch"><span/><button onClick={awaken}>{state?.transcript?.length?'Pick up where we left off':'Touch the ring'} <ArrowUpRight size={13}/></button><small>{state?.transcript?.length?'Nothing’s lost.':'Your Persona is right here.'}</small></div>}</div>
 <div className="exact-vignette" style={{opacity:open?1:0,background:`radial-gradient(circle at ${g.ringX}px ${g.ringY}px,#fcfcfc00 0,#fcfcfc00 ${g.mobile?120:Math.round(W*.1)}px,#fcfcfc80 ${g.mobile?420:Math.round(W*.5)}px,#fcfcfcd9 150%)`}}/><div className="exact-beam halo" style={{opacity:open?1:0,clipPath:`polygon(${g.ringX-radius*1.3}px ${g.ringY-radius*.2}px,${g.ringX+radius*1.3}px ${g.ringY-radius*.2}px,${g.panelL+g.panelW+6}px ${panelBottom+2}px,${g.panelL-6}px ${panelBottom+2}px)`}}/><div className="exact-beam" style={{opacity:open?1:0,clipPath:`polygon(${g.ringX-radius*.62}px ${ringTop}px,${g.ringX+radius*.62}px ${ringTop}px,${g.panelL+g.panelW-18}px ${panelBottom}px,${g.panelL+18}px ${panelBottom}px)`}}/>
 <section ref={panel} className="exact-panel" style={{left:g.panelL,top:g.panelTop,width:g.panelW,height:g.panelH,borderRadius:g.mobile?26:29,opacity:open?1:0,visibility:open?'visible':'hidden',pointerEvents:open?'auto':'none',transform:open?'translate3d(0,0,0) rotateX(3deg) scale(1)':panelClosed,transition:open?'transform .56s cubic-bezier(.2,.75,.2,1) .25s,opacity .12s .25s,visibility 0s':'transform .38s cubic-bezier(.55,0,.8,.3) .12s,opacity .12s .4s,visibility 0s .52s'}}><div className="exact-glass"/><header className="exact-panel-head"><div className={`exact-mini-ring ${live?status:incoming?'incoming':'active'}`}><span/></div><div><strong>{agent}</strong><small>{live?(muted?'Mic paused':status==='speaking'?'Speaking':status==='thinking'?'Thinking':'Listening'):incoming?'Calling…':state?.agentName?'Here with you':'A first hello'}</small></div><span className="exact-spacer"/>{state?.agentName&&<button onClick={()=>setSheet('memory')}>•••</button>}<button onClick={close}><Minus size={17}/></button></header>{error&&<div className="exact-error">{error}<button onClick={()=>setError('')}><X size={13}/></button></div>}{!state?<div className="exact-loading">Waking up…</div>:scene==='naming'?<Naming value={name} setValue={setName} busy={busy} send={send}/>:scene==='incoming'?<Incoming agent={agent} decline={decline} answer={startCall}/>:scene==='voice'?<Voice agent={agent} status={status} caption={caption||lastAgent?.text} muted={muted} level={level} setMuted={setMuted} call={call} setView={setView} endCall={endCall} gmailCard={lastAgent?.card?.type==='gmail'&&!lastAgent.card.closed} openGmail={()=>setSheet('gmail')}/>:<Chat state={state} agent={agent} transcript={transcript} messagesRef={messages} busy={busy} text={text} setText={setText} send={send} live={live} setView={setView} startCall={startCall} openGmail={()=>setSheet('gmail')} config={config}/>}<footer className="exact-panel-foot"><i/>{live?'Voice and text, together.':connected?'Your inbox stays read-only.':'Your conversation stays with you.'}<Lock size={10}/></footer><Sheet sheet={sheet} setSheet={setSheet} state={state} agent={agent} config={config} gmail={gmail} gmailBusy={gmailBusy} event={event} reset={reset}/></section></main>
 <footer className="exact-foot" style={{height:g.footH,left:g.mobile?22:'5%',right:g.mobile?22:'5%'}}><span>Made to feel <em>personal.</em></span><button onClick={open?close:awaken}>{open?'Tap the ring to tuck this away.':state?.transcript?.length?'Pick up here anytime.':'No forms. Just a first hello.'}</button>{!g.mobile&&<span>PERSONA · INTERACTIVE CONCEPT</span>}</footer>{!open&&live&&<button className="exact-floating" onClick={reopen}><Phone size={15}/>{agent} · call in progress</button>}</div>
 <section className="exact-product"><span>WHILE YOU GET ON WITH YOUR DAY</span><h2>It handles the rest.<br/><em>Then lets you know.</em></h2><p>Calls, bookings, errands and inbox, each one reported back when it’s done.</p><img src={`${A}/completions.png`} alt="Persona Band surrounded by completed tasks"/></section><section className="exact-choose"><h2>Your Persona is waiting.<br/>Choose <em>yours</em>.</h2><img src={`${A}/lineup.png`} alt="Persona Band in eight colours"/><button onClick={()=>{scrollTo({top:0,behavior:reduced.current?'auto':'smooth'});later(650,awaken)}}>Touch the ring <ArrowUp size={13}/></button><small>Product images from yourpersona.com/band</small></section></div>
}

function Naming({value,setValue,busy,send}){return <div className="exact-naming"><div className="exact-hud"><Mark/><span/></div><span className="exact-overline">LET’S MAKE THIS PERSONAL</span><h2>First, a name.</h2><p>What would you like to call me?</p><form onSubmit={e=>{e.preventDefault();if(value.trim()&&!busy)send(value.trim())}}><div><input value={value} onChange={e=>setValue(e.target.value)} maxLength={32} placeholder="A name that feels right"/><button disabled={!value.trim()||busy}><ArrowUp size={18}/></button></div><nav>{['Nova','Cleo','Atlas'].map(n=><button type="button" key={n} onClick={()=>setValue(n)}>{n}</button>)}<button type="button" onClick={()=>send('You pick a name for yourself')}>You choose</button></nav></form></div>}
function Incoming({agent,decline,answer}){return <div className="exact-incoming"><div className="exact-hud pulse"><Mark/><span/></div><span className="exact-overline">A QUICK HELLO</span><h2>{agent} is calling.</h2><p>Tell me a little about yourself.<br/>No script. Start anywhere.</p><div><button className="light" onClick={decline}><Keyboard size={16}/>Keep typing</button><button className="dark" onClick={answer}><Phone size={16}/>Answer</button></div></div>}
function Voice({agent,status,caption,muted,level,setMuted,call,setView,endCall,gmailCard,openGmail}){return <div className="exact-voice"><div className={`exact-hud ${status}`} style={{'--level':level}}><Mark/><span/></div><span className="exact-overline">{muted?'MICROPHONE PAUSED':status==='speaking'?agent.toUpperCase():(status||'listening').toUpperCase()}</span><p>{caption||(status==='listening'?(muted?'I’ll wait.':'I’m listening.'):'…')}</p>{gmailCard&&<button className="exact-gmail-nudge" onClick={openGmail}><img src={`${A}/gmail.svg`} alt=""/>Connect Gmail while we talk<ArrowUpRight size={13}/></button>}<div className="exact-controls"><button onClick={()=>{call.current?.setMuted(!muted);setMuted(!muted)}}>{muted?<MicOff size={19}/>:<Mic size={19}/>}<span>{muted?'Unmute':'Mute'}</span></button><button onClick={()=>setView('text')}><Keyboard size={19}/><span>Text</span></button><button className="hangup" onClick={endCall}><PhoneOff size={19}/><span>End call</span></button></div></div>}
function Chat({state,agent,transcript,messagesRef,busy,text,setText,send,live,setView,startCall,openGmail,config}){return <><div className="exact-messages" ref={messagesRef}>{transcript.map((m,i)=>m.role==='system'?<div className="exact-system" key={m.id}>{m.text}</div>:<div className={`exact-message ${m.role}`} key={m.id}><small>{m.role==='user'?'You':agent}</small><p>{m.text}</p>{m.brief&&<div className="exact-brief"><header><img src={`${A}/gmail.svg`} alt=""/><strong>Your inbox, lighter.</strong>{m.brief.simulated&&<small>Sample</small>}</header>{m.brief.items.map((item,n)=><div key={n}><span>{item.label}</span><strong>{item.from}</strong><p>{item.why}</p></div>)}</div>}{m.card?.type==='gmail'&&!m.card.closed&&state.gmail.status!=='connected'&&<button className="exact-gmail-nudge" onClick={openGmail}><img src={`${A}/gmail.svg`} alt=""/>{config?.googleClientId?'Connect Gmail':'Try the sample inbox'}<ArrowUpRight size={13}/></button>}{i===transcript.length-1&&m.suggest&&<nav className="exact-suggestions">{m.suggest.map(s=><button key={s} onClick={()=>send(s)}>{s}</button>)}</nav>}</div>)}{busy&&<div className="exact-thinking"><i/><i/><i/></div>}</div><form className="exact-composer" onSubmit={e=>{e.preventDefault();if(!text.trim()||busy)return;send(text);setText('')}}><button type="button" onClick={live?()=>setView('voice'):startCall}><Mic size={18}/></button><input value={text} onChange={e=>setText(e.target.value)} placeholder={`Tell ${agent} what’s on your mind`} maxLength={2000}/><button className="send" disabled={!text.trim()||busy}><ArrowUp size={17}/></button></form></>}
function Sheet({sheet,setSheet,state,agent,config,gmail,gmailBusy,event,reset}){return <div className="exact-sheet" aria-hidden={!sheet} style={{transform:sheet?'translateY(0)':'translateY(104%)',visibility:sheet?'visible':'hidden'}}><button className="exact-back" onClick={()=>setSheet(sheet==='reset'?'memory':null)}><ChevronLeft size={15}/>{sheet==='reset'?'Back':'Back to conversation'}</button>{sheet==='gmail'?<><div className="exact-service"><img src={`${A}/gmail.svg`} alt="Gmail"/></div><h2>A little context.<br/>A lot less explaining.</h2><p>Connect Gmail so {agent} can look at recent senders, subjects and previews with you.</p><ul><li>Read-only. Nothing can be sent, deleted or changed.</li><li>Reads recent senders, subjects and message previews.</li><li>A small inbox snapshot reaches this app and its configured model.</li></ul>{state.gmail.status==='connected'?<div className="exact-connected"><Check size={16}/>{state.gmail.email}{state.gmail.simulated?' · sample':''}</div>:<div className="exact-stack">{config?.googleClientId?<button className="dark" onClick={()=>gmail(false)} disabled={gmailBusy}>{gmailBusy?'Connecting…':'Continue with Google'}</button>:<button className="dark" onClick={()=>gmail(true)} disabled={gmailBusy}>{gmailBusy?'Connecting…':'Explore a sample inbox'}</button>}<button onClick={()=>{event({type:'gmail_skipped'}).catch(()=>{});setSheet(null)}}>Not now</button></div>}</>:sheet==='memory'?<><h2>The little things<br/>worth remembering.</h2><p>Picked up from our conversation.</p><dl>{[['Your Persona',state.agentName],['Your name',state.userName],['On your mind',state.need],['Gmail',state.gmail.status==='connected'?(state.gmail.simulated?'Sample inbox':state.gmail.email):'Not connected']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'We’ll get to it.'}</dd></div>)}</dl><button className="exact-reset" onClick={()=>setSheet('reset')}><RotateCcw size={13}/>Start fresh</button></>:sheet==='reset'?<><h2>A fresh start?</h2><p>This removes your conversation, saved names and inbox snapshot. It can’t be undone.</p><div className="exact-stack"><button className="dark" onClick={reset}>Forget this conversation</button><button onClick={()=>setSheet('memory')}>Keep it</button></div></>:null}</div>}
